fdt.cc
This adds/moves calls to `input.next_token()` to help parse the Linux dts files.
=> Fix parsing of whitespace

fdt.cc
In C, `strchr(3)` returns a `char*`, whereas C++ defines two overloads:
* `const char *strchr(const char*, int)`
* `char *strchr(char*, int)`
Building fdt.cc with libc++ 3.9.0 was failing because [libc++ r260377](http://llvm.org/viewvc/llvm-project?view=revision&revision=260337)
added the first overload to string.h, leading to failures such as:
fdt.cc:1638:8: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
Just define `val` as a `const char*` to fix it.
=> fdt: Expect strchr() to return a const char*.

input_buffer.cc
Initialize correct parent in binary_operator's constructor.
Include <errno.h> explicitly. Without NDEBUG, errno was declared as
a side effect of including <iostream>.
Obtained from FreeBSD r313709 by dim@FreeBSD.org.
=> fix build when NDEBUG is defined

input_buffer.cc
This is all in input_buffer.cc .
=> Add missing "typename" in divmod's  "using" of binary_operator_base::result

dtc.cc
Version output should be on stdout as most of the tools that parse this
information don't play with redirection.
Also add a 'gnu compatible' version (For now matching on 1.4.0)
U-Boot check the version for some target so we need some compliance on this.
Signed-off-by: Emmanuel Vadot <manu@freebsd.org>
=> version output fix

Tests/cross_reference.dts, Tests/cross_reference.dts.expected, fdt.cc
The null char need to be at the end.
Fix issue #20
Signed-off-by: Emmanuel Vadot <manu@freebsd.org>
=> Fix resolve_cross_reference

Tests/localfixups_multinode.at.dts, Tests/localfixups_multinode.at.dts.expected, Tests/localfixups_multioffset.at.dts, Tests/localfixups_multioffset.at.dts.expected, Tests/localfixups_multiprop.at.dts, Tests/localfixups_multiprop.at.dts.expected
The eventually agreed-upon `/__local_fixups__` output differs from what we currently
write, though how we write it seems logical/consistent. Fix the resolve test
case to match how it *should* be, and add three more test cases for more complex
scenarios to make sure we're generating is as expected by libfdt and other
consumers of overlays.
These test cases go along with Issue #27 -- they were generated by compiling the .dts to .dtbo with GPL dtc(1) and then converting back to .dts with BSD dtc(1), and match what I expect to see based on libfdt's `/__local_fixups__` handling code [1].
[1] https://github.com/dgibson/dtc/blob/master/libfdt/fdt_overlay.c#L218
=> Add/amend tests for proper /__local_fixups__

Tests/overlay_sugar.at.dts, Tests/overlay_sugar.at.dts.expected, fdt.cc, fdt.hh
This syntactic sugar might be best explained by the test, but it generally exists to transform:
```
&foo {
prop = "value";
};
```
into
```
/ {
fragment@0 {
target = <&foo>;
__overlay__ {
prop = "value";
};
};
};
```
It is meant to take a little bit of edge off of creating overlays, making it more natural to other .dts concepts.
I note here that GPL dtc(1) currently has some weird behavior if you mix traditional overlay fragments with this new syntax, as I've done in this test. Their weird behavior ranges from rejecting duplicate node names (OK) to silently merging the nodes and keeping one of the target properties.
I'll take this behaviors up with them, but I think how I've implemented this here is a safe bet, given that I don't think it will be valid to try and merge one of our ad-hoc …
=> Syntactic sugar for overlays

Tests/testexpected.sh, fdt.cc, fdt.hh
- Properly initialize is_plugin; some non-/plugin/ dtb were getting generated with /__fixups__ and /__local_fixups__
- Don't try and re-assign unit addresses on non-fragment nodes
- Explicitly check exit code of dtc|diff now that it's no longer the exit code of the script
=> Fix some regressions caused by recent additions

Makefile, dtc.cc
The only warnings that actually crop up are due to the version_* variables being local to the compilation unit and not being static (and not being declared elsewhere as 'extern').
Fix this, remove WARNS so we just catch these things as they crop up later.
=> Fix warnings when WARNS=6, remove WARNS override

CMakeLists.txt
This has made development much better on my end, only having to remember to enable debug to include the tests. I've made it ignore ENABLE_TESTS since I've not yet found a reason that I'd want a debug build with tests explicitly turned off.
=> Enable tests automatically for debug builds

dtc.cc
This matches GPL dtc behavior as well as a generally observed behavior.
=> Output to stdout if "-" is passed for -o option.

fdt.cc, fdt.hh
The callable's return value may indicate whether the recursion should happen or
not. `parent` as passed to `visit` will be passed on to the callable, and the
recursive call will pass the current node as the parent to its children.
I've submitted this separately from /delete-if-unreferenced/ since it's worth of review on its own.
=> Extend node::visit to include parent node and allow control of recursion

Tests/overlay_sugar.at.dts, Tests/overlay_sugar.at.dts.expected, dtc.1, fdt.cc, fdt.hh
This syntax was added to GPL dtc in this commit: https://github.com/dgibson/dtc/commit/8f1b35f88395adea01ce1100c5faa27dacbc8410
Add the equivalent to our dtc, so that the following overlay:
```
/dts-v1/;
/plugin/;
&{/soc} {
foo = "bar";
};
```
will effectively be turned into the following:
```
/dts-v1/;
/plugin/;
/ {
fragment@0 {
target-path = "/soc";
__overlay__ {
foo = "bar";
};
};
};
```
=> Add path-based syntactic sugar

Tests/localfixups_fragment_unit.at.dts, Tests/localfixups_fragment_unit.at.dts.expected, fdt.cc
Do not omit unit number when generating __local_fixups__ entries
in overlay, the name in the section should match the name of the
node to fix up exactly
=> Fix __local_fixup__ pathes with unit number in the name

dtb.cc
If consumption fails, we cannot trust that 'magic' was populated with
anything useful.  To compound on this, 'magic' is initialized with
0xd00dfeed.  These facts combined meant that piping completely broken or
missing output into dtc would always result in an error message like:
Missing magic token in header.  Got d00dfeed expected 0xd00dfeed
Which is wrong, since it most certainly did not get d00dfeed. Instead of
removing the initialization, just split it out so we have two obviously
different error cases: Missing magic token, and incorrect magic token.
=> Split out consumption of magic number from magic number check

CMakeLists.txt
Trying to wrap the super-long string is a no-start, and breaking it down into separate set()'s yields 8+ lines of set() and it's even more irritating... open to ideas.
=> Add CXXFLAGS associated with WARNS=6

Tests/overlay_nosym.dts, Tests/overlay_nosym.dts.expected, fdt.cc
All of the /__fixups__ and /__local_fixups__ generation was gated by -@.
This is not a strict requirement for overlays, though, and it works fine
with GPL dtc.
A test case has been added for this case.
=>  Fix compilation of overlays without -@

string.cc, util.hh
When building against libstdc++ these headers aren't pulled in implicitly
=> Don't depend on implicit header dependencies

HACKING
I've been told that this is where dev happens, and then it gets pulled into svn, update the pointer.
=> point to the git repo as source of truth, not svn

Tests/delete_node_newsym.dts, Tests/delete_node_newsym.dts.expected, fdt.cc
This was encountered in the wild - deleted nodes can be reincarnated immediately after a /delete-node/ directive and are expected to be usable. Do the deletions before we merge anything to match GPL dtc behavior.
=> Fix ordering of /delete-node/ and /delete-property/ deletion to match GPL dtc

fdt.cc, fdt.hh
As requested by David:
- Documentation for several fields and methods added
- A flag for the device_tree having encountered an /omit-if-no-ref/ has been added to avoid the extra expense
I'm still working through the details of how to tell that a node's being kept alive because of one of its descendants. The two approaches I see at the moment of determining the node's heritage are either a tree walk for each of the nodes we're marking as 'seen' (incredibly not ideal), or storing the path to each node in the tree for comparisons' sake. The latter seems like a more viable option. I'd also need to change the 'used' tracking into more of a ref-count rather than the current single-bit so we can check `used == 1 && used_by_descendant`, but that's not much of an issue.
=> Some cleanup from /omit-if-no-ref/

fdt.cc
node::parse will return 0 instead of a valid pointer if the node it parsed was
ultimately not valid.  This bit failed to check for that.
=> Fix segfault when errors happen while compiling a path-ref node

dtc.cc, fdt.hh
This matches the behavior of GPL dtc; for instance, if -I dts is specified,
then -O dtb is assumed. -I dtb assumes -O dts, and all of this works in
reverse as well if just -O is specified.
We still default to -I dts -O dtb if both are omitted or -I dts if -O asm is
specified.
Signed-off-by: Kyle Evans <kevans@FreeBSD.org>
=> dtc: assume proper -I/-O formats if only one is specified

Tests/memreserve.dts, Tests/memreserve.dts.expected, fdt.cc
Testing and attempting to use dtc to parse out /memreserve/ nodes in the RPi DTB yielded a somewhat major issue in our dtc- there were no /memreserve/ in the output! This series fixes that and a couple of other issues with the handling; the commit messages describe the various issues I ran into.
=> Collection of fixes for /memreserve/ handling

dtc.cc
Since we don't set opterr to 0, getopt prints a message when it
encounters an unknown/invalid option. We therefore don't need to
print our own message in the default handler.
=> dtc: remove unknown option printf, since getopt will print it

dtb.cc
FreeBSD 10.3 requires this, and dtc is a bootstrap tool so it needs to
compile there.
This is FreeBSD r353961
=> exit requires stdlib.h to be included for use

Makefile, Makefile.depend
This is the only non-upstreamed diff left in FreeBSD across all files.
=> Sync Makefile(.depend) with FreeBSD versions

dtc.1
Per @0mp's hint, use `\&` to silence mandoc warnings. While here, fix a typo and bump the date.
=> dtc.1: Fix the display of directives ending with semicolons

fdt.cc, input_buffer.cc
It seems that recent libstdc++ pulls in fewer headers implicitly, so this
is needed to avoid compilation errors due to missing std::numeric_limits<>.
Co-authored-by: John Baldwin <jhb@FreeBSD.org>
See https://github.com/CTSRD-CHERI/cheribsd/commit/c05532bebd36c84aeebf16b734595c5b443fbde6 and  https://github.com/CTSRD-CHERI/cheribsd/pull/1331
=> Add missing <limits> includes

Makefile
This was added before Clang bumped the default to C++11 and is no longer needed.
Close #74
=> Remove C++11 standard constrain

.github/workflows/main.yml
To avoid warnings about upgrading from a deprecated node version.
References:	https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
=> GitHub: Update actions/checkout version

Makefile
This is in line with dcd8a4cd5fb509da34e287db4570b7b9a11f2d57.
Given FreeBSD does not use `CMakeLists.txt`.
=> Ensure that dtc is built in C++17 mode
